"""API integration tests.

Runs against a real ONNX session (real model or dummy generated by
scripts/create_dummy_model.py). No mocking — tests the full request path.
"""

import subprocess
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

ARTIFACTS_DIR = Path(__file__).parent.parent / 'app' / 'artifacts'
DUMMY_SCRIPT  = Path(__file__).parent.parent / 'scripts' / 'create_dummy_model.py'


def _ensure_artifacts() -> None:
    """Generate dummy model if artifacts are missing (e.g. fresh CI clone)."""
    if not (ARTIFACTS_DIR / 'model.onnx').exists():
        subprocess.run(
            [sys.executable, str(DUMMY_SCRIPT)],
            check=True,
            capture_output=True,
        )


def _valid_signal() -> list[float]:
    return [0.0] * 1024


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope='module')
def client():
    _ensure_artifacts()
    # Import after ensuring artifacts exist so BearingClassifier can load.
    from app.main import app
    with TestClient(app) as c:
        yield c


# ---------------------------------------------------------------------------
# /health
# ---------------------------------------------------------------------------

def test_health_returns_200(client):
    resp = client.get('/health')
    assert resp.status_code == 200


def test_health_body(client):
    resp = client.get('/health')
    assert resp.json() == {'status': 'ok'}


# ---------------------------------------------------------------------------
# /predict — happy path
# ---------------------------------------------------------------------------

def test_predict_returns_200(client):
    resp = client.post('/predict', json={'signal': _valid_signal()})
    assert resp.status_code == 200


def test_predict_response_shape(client):
    resp = client.post('/predict', json={'signal': _valid_signal()})
    body = resp.json()
    assert 'predicted_class' in body
    assert 'label' in body
    assert 'probabilities' in body
    assert 'inference_time_ms' in body


def test_predict_class_is_known(client):
    resp = client.post('/predict', json={'signal': _valid_signal()})
    known = {'normal', 'inner_race', 'ball', 'outer_race'}
    assert resp.json()['predicted_class'] in known


def test_predict_label_matches_class(client):
    class_names = ['normal', 'inner_race', 'ball', 'outer_race']
    resp = client.post('/predict', json={'signal': _valid_signal()})
    body = resp.json()
    assert class_names[body['label']] == body['predicted_class']


def test_predict_probabilities_sum_to_one(client):
    resp = client.post('/predict', json={'signal': _valid_signal()})
    total = sum(resp.json()['probabilities'].values())
    assert abs(total - 1.0) < 1e-5


def test_predict_all_four_classes_in_probabilities(client):
    resp = client.post('/predict', json={'signal': _valid_signal()})
    assert set(resp.json()['probabilities'].keys()) == {
        'normal', 'inner_race', 'ball', 'outer_race'
    }


def test_predict_inference_time_is_positive(client):
    resp = client.post('/predict', json={'signal': _valid_signal()})
    assert resp.json()['inference_time_ms'] > 0


# ---------------------------------------------------------------------------
# /predict — invalid input (422 Unprocessable Entity)
# ---------------------------------------------------------------------------

def test_predict_too_short_returns_422(client):
    resp = client.post('/predict', json={'signal': [0.0] * 512})
    assert resp.status_code == 422


def test_predict_too_long_returns_422(client):
    resp = client.post('/predict', json={'signal': [0.0] * 2048})
    assert resp.status_code == 422


def test_predict_empty_signal_returns_422(client):
    resp = client.post('/predict', json={'signal': []})
    assert resp.status_code == 422


def test_predict_missing_field_returns_422(client):
    resp = client.post('/predict', json={})
    assert resp.status_code == 422


def test_predict_wrong_type_returns_422(client):
    resp = client.post('/predict', json={'signal': 'not_a_list'})
    assert resp.status_code == 422
